### ISSUE TITLE
Make connector.class configurable for charts/kafka-connect/templates/secret.yaml

### ISSUE THREAD

**Issue by py4mac** [w6d-io/charts#76]
Hello

Could you please make "connector.class" configurable for "charts/kafka-connect/templates/secret.yaml"

"connector.class": "io.debezium.connector.postgresql.PostgresConnector"

I propose to add a value for that

`"connector.class": {{ default "io.debezium.connector.postgresql.PostgresConnector" .Values.connector.class | quote }},`

Thanks,
Py

**Comment by david972** [comment]
Hi,

thank will be done in the next version
